spring:
  profiles:
    include:
    - oauth
    - aws
    - firebase
    default : dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  batch: 
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    username: DELETED
    port: '587'
    password: DELETED
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: DELETED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: DELETED
    url: jdbc:mysql://localhost:3306/commonssafy?characterEncoding=UTF-8&rewriteBatchedStatements=true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    org:
      hibernate: info
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      ssafy:
        gumid101: debug
  file:
    max-history: 7
    max-size: 100MB
    name: logs/server_log.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log

server:
  servlet:
    context-path: /api
  port: '8080'

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: DELETED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: DELETED
    url: jdbc:mysql://localhost:3306/commonssafy?characterEncoding=UTF-8&rewriteBatchedStatements=true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
---  
spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    password: DELETED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: DELETED
    url: jdbc:mysql://host.docker.internal:13306/commonssafy?characterEncoding=UTF-8&rewriteBatchedStatements=true
  redis:
    host: redis
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
